remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Dambai College of Education Research Resources]
description: [This site houses books, articles, proceedings, websites, etc. to enhance research]
